name: Test deploy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package


  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      Host_Port: 3111
      Service_Port: 8080
      Container_Name: test
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo running on branch: ${{ github.head_ref }}
          echo name of Pull Request: ${{ github.event.pull_request.title }}
          echo type of deployment: ${{ env.Container_Name }}

          rm -rf ${{ github.event.repository.name }}
          docker stop ${{ github.event.repository.name }}-${{ env.Container_Name }} &> /dev/null || true
          docker rm ${{ github.event.repository.name }}-${{ env.Container_Name }} &> /dev/null || true
          docker image rm ${{ github.event.repository.name }}-${{ env.Container_Name }} &> /dev/null || true

          git clone https://github.com/Brigade-2/${{ github.event.repository.name }}.git -b ${{ github.head_ref }} 
          cd ${{ github.event.repository.name }}

          docker build . -t ${{ github.event.repository.name }}-${{ env.Container_Name }}
          docker run -d -p ${{ env.Host_Port }}:${{ env.Service_Port }} --name ${{ github.event.repository.name }}-${{ env.Container_Name }} ${{ github.event.repository.name }}-${{ env.Container_Name }}